version: '3.8'

services:
  fastapi-server:
    build: .
    container_name: code-judge
    privileged: true
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/codejudge
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codejudge
    ports:
      - "5432:5432"
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
