"""empty message

Revision ID: 21e96300b926
Revises: 84ba4d3dd723
Create Date: 2024-08-31 19:48:23.291430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21e96300b926'
down_revision: Union[str, None] = '84ba4d3dd723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('problem_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'testcase', 'problem', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testcase', type_='foreignkey')
    op.drop_column('testcase', 'problem_id')
    # ### end Alembic commands ###
