"""Added cses_problem_id field attr to CSESProblemRequest.

Revision ID: b6c0108ef031
Revises: 7acf53599174
Create Date: 2024-09-01 22:27:39.310619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6c0108ef031'
down_revision: Union[str, None] = '7acf53599174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csesproblemrequest', sa.Column('problem_id', sa.Integer(), nullable=True))
    op.alter_column('csesproblemrequest', 'cses_problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('csesproblemrequest_cses_problem_id_fkey', 'csesproblemrequest', type_='foreignkey')
    op.create_foreign_key(None, 'csesproblemrequest', 'problem', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'csesproblemrequest', type_='foreignkey')
    op.create_foreign_key('csesproblemrequest_cses_problem_id_fkey', 'csesproblemrequest', 'problem', ['cses_problem_id'], ['id'])
    op.alter_column('csesproblemrequest', 'cses_problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('csesproblemrequest', 'problem_id')
    # ### end Alembic commands ###
